# Generated by Django 3.2.4 on 2021-07-25 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-name',), 'verbose_name_plural': 'products'},
        ),
    ]
