# Generated by Django 3.2.4 on 2021-08-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_post_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
