# Generated by Django 3.2.4 on 2021-08-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20210802_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='заголовок')),
                ('subtitle', models.CharField(max_length=50, verbose_name='заголовок')),
                ('text', models.TextField(blank=True, verbose_name='текст')),
                ('picture', models.ImageField(blank=True, upload_to='slides/', verbose_name='слайд')),
            ],
        ),
    ]
