# Generated by Django 3.2.4 on 2021-08-12 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_auto_20210812_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidetextitem',
            name='text',
            field=models.CharField(max_length=50, null=True, verbose_name='позиция'),
        ),
        migrations.AlterField(
            model_name='slidetextitem',
            name='textItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='notes.slide', verbose_name='пункт'),
        ),
    ]
