# Generated by Django 3.2.4 on 2021-08-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_auto_20210812_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ('text',), 'verbose_name': 'слайд', 'verbose_name_plural': 'слайды'},
        ),
        migrations.AddField(
            model_name='slide',
            name='link',
            field=models.CharField(blank=True, max_length=50, verbose_name='сссылка'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='text',
            field=models.CharField(blank=True, max_length=50, verbose_name='текст'),
        ),
    ]
