# Generated by Django 3.2.4 on 2021-08-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_auto_20210812_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='target',
            field=models.CharField(blank=True, max_length=50, verbose_name='вкладка'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='link',
            field=models.CharField(blank=True, max_length=50, verbose_name='ссылка'),
        ),
    ]
