# Generated by Django 3.2.4 on 2021-08-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transport',
            field=models.CharField(choices=[('курьером', 'курьером'), ('самовывоз', 'самовывоз')], max_length=20, verbose_name='условия доставки'),
        ),
    ]
