# Generated by Django 3.2.4 on 2021-08-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Ready for pickup', 'Ready for pickup'), ('Completed', 'Completed')], default='Created', max_length=20, verbose_name='статус заказа'),
        ),
    ]
