# Generated by Django 3.2.4 on 2021-08-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Создан', 'Создан'), ('В процессе сборки', 'В процессе сборки'), ('Отправлен получателю', 'Отправлен получателю'), ('Готов к выдаче', 'Готов к выдаче'), ('Завершен', 'Завершен')], default='Created', max_length=20, verbose_name='статус заказа'),
        ),
    ]
