# Generated by Django 3.2.4 on 2021-08-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100, verbose_name='ссылка на оплату заказа')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Создан'), ('Paid', 'Оплачен'), ('Shipped', 'Отправлен получателю'), ('Ready for pickup', 'Готов к выдаче'), ('Completed', 'Завершен')], default='Создан', max_length=20, verbose_name='статус заказа'),
        ),
    ]
